/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "simplewebstreaming-20210125194820-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d355h0s62btcyd.cloudfront.net",
    "aws_cognito_identity_pool_id": "us-east-1:70d68663-a49c-4b2c-bf24-60c48289ab9f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dQRnvkNWG",
    "aws_user_pools_web_client_id": "1086bnpbgcns0ns11194ilio9i",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "IVSparam-dev",
            "region": "us-east-1"
        },
        {
            "tableName": "ISS-task-dns-track-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "saveIVSparam",
            "endpoint": "https://ohc69dctab.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
